from pycompss.api.task import task
from pycompss.api.binary import binary
from pycompss.api.constraint import constraint
from pycompss.api.parameter import *
import csv
import os

MASA_BINARY = "masa-openmp"


@task(returns=str)
def create_dir(dir):
    import os
    os.makedirs(dir, exist_ok=True)
    return dir


@constraint(computing_units="1")
@binary(binary="masa-openmp", args="--alignment-edges=++ --work-dir {{work_dir}} {{input_1}} {{input_2}}")
@task(work_dir=IN, input_1=FILE_IN, input_2=FILE_IN, alignment_file=INOUT)
def masa(work_dir, input_1, input_2, alignment_file):
    """Runs the MASA binary through pycompss

     Args:
         work_dir (str): the working directory parameter
         input_1 (str): name of the first fasta file
         input_2 (str): name of the second fasta file
     """
    pass


@task(pair_dir=IN, alignment_file=INOUT, returns=dict)
def get_metrics(pair_dir, alignment_file, seq1_ac, seq2_ac):
    """Get the metrics from a pair-wise alignment file generated by the MASA execution
     extracting the needed metadata, as Total score, Matches, Mismatches, Gap openings, and Gap extentions.

     Args:
         alignment_file (str): pair-wise alignment file generated by the MASA execution

     Returns:
         dict: dictionary contaning the metrics of the alignment file
     """
    import re
    import os
    from pathlib import Path
    from pycompss.api.api import compss_open
    metrics = dict()
    with compss_open(str(alignment_file), "r") as f:
        text = f.read()
        total_score_str = re.findall(r"Total Score:\s+\d+", text)
        matches_str = re.findall(r"Matches:\s+\d+", text)
        mismatches_str = re.findall(r"Mismatches:\s+\d+", text)
        gap_openings_str = re.findall(r"Gap Openings:\s+\d+", text)
        gap_extentions_str = re.findall(r"Gap Extentions:\s+\d+", text)
        if len(total_score_str) > 0:
            metrics["total_score"] = float(
                (total_score_str[0].split(":")[1]).strip())
        if len(matches_str) > 0:
            metrics["matches"] = float(
                (matches_str[0].split(":")[1]).strip())
        if len(mismatches_str) > 0:
            metrics["mismatches"] = float(
                (mismatches_str[0].split(":")[1]).strip())
        if len(gap_openings_str) > 0:
            metrics["gap_openings"] = float(
                (gap_openings_str[0].split(":")[1]).strip())
        if len(gap_extentions_str) > 0:
            metrics["gap_extentions"] = float(
                (gap_extentions_str[0].split(":")[1]).strip())
        metrics["sequence_1"] = seq1_ac
        metrics["sequence_2"] = seq2_ac
    return metrics


@task(multifasta_file=FILE_IN, sequence_dir=IN, returns=list)
def split_sequences(multifasta_file, sequence_dir):
    """Split a multifasta file into N fasta files, with one sequence each

     Args:
         multifasta_file (str): multifasta file containning the sequences

     Returns:
         dict: List of all the sequences files
     """
    from Bio import SeqIO
    import os
    records = list(SeqIO.parse(multifasta_file, "fasta"))
    record_ids = list()
    for r in records:
        if len(r.id) > 8:
            seq_id = r.id[:8]
        else:
            seq_id = r.id
        out_file = os.path.join(sequence_dir, f"{seq_id}.fasta")
        SeqIO.write(r, out_file, "fasta")
        record_ids.append(f"{seq_id}.fasta")
    return record_ids


@task(metrics=IN, returns=float)
def compute_identity(metrics):
    matches = float(metrics["matches"])
    mismatches = float(metrics["mismatches"])
    gap_openings = float(metrics["gap_openings"])
    gap_extentions = float(metrics["gap_extentions"])

    alignment_length = matches + mismatches + gap_openings + gap_extentions

    if alignment_length == 0:
        return 0.0

    return (matches / alignment_length) * 100.0


@task(pairs=IN, sequences=IN, k=IN, similar=IN, returns=list)
def maxmin_selection(pairs, sequences, k, similar):
    similarity = {s: {} for s in sequences}

    for s1, s2, identity in pairs:
        similarity[s1][s2] = identity
        similarity[s2][s1] = identity

    if not similar:
        distance = {
            s: {
                t: 100.0 - similarity[s][t]
                for t in similarity[s]
            }
            for s in similarity
        }
    else:
        distance = similarity

    avg_metric = {}
    for s in sequences:
        if distance[s]:
            avg_metric[s] = sum(distance[s].values()) / len(distance[s])
        else:
            avg_metric[s] = 0.0

    selected = [max(avg_metric, key=avg_metric.get)]

    while len(selected) < k:
        best_seq = None
        best_score = -1.0

        for s in sequences:
            if s in selected:
                continue

            values = [distance[s][x] for x in selected if x in distance[s]]
            if not values:
                continue

            min_value = min(values)

            if min_value > best_score:
                best_score = min_value
                best_seq = s

        if best_seq is None:
            break

        selected.append(best_seq)

    return selected


@task(selected=COLLECTION_IN, sequence_dir=IN, output_fasta=FILE_OUT)
def write_selected_sequences(selected, sequence_dir, output_fasta):
    with open(output_fasta, "w") as out:
        for seq_file in selected:
            with open(os.path.join(sequence_dir, seq_file)) as f:
                out.write(f.read())


@task(pairs=COLLECTION_IN, output_csv=FILE_OUT)
def write_pairwise_csv(pairs, output_csv):
    with open(output_csv, "w", newline="") as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(["seq1", "seq2", "identity"])
        for s1, s2, identity in pairs:
            writer.writerow([s1, s2, round(identity, 4)])

# @constraint(computing_units="1")


@binary(binary="msa_pastar", args="-f {{output}} -t {{threads}} {{input_}}")
@task(output=FILE_OUT, threads= IN, input_=FILE_IN)
def pastar(output, threads, input_):
    pass
